### ISSUE TITLE
Doesn't follow discord.py style of naming

### ISSUE THREAD

**Issue by TheOnlyWayUp** [k0vu/Ejactcord.py#1]
You're trying to make an extension library, consider following practices used in discord.py, dpy adheres to pep8, so snake_case instead of camelCase. It isn't object oriented either, why is click a method of bot rather than it being one of an interaction object? Why is sendEmbed a method of bot instead of it being one of a channel object?

If you're going to make an extension library, try to model it off if the parent one.

**Comment by de-contained** [comment]
1. This isn't an extension, just a code used for discord.py,
2. The pressing button function was just practice and is manually configurable by the user. Therefore, you'd have to fetch components, get the custom id's, and click the button.
